app:
    resource: '@AppBundle/Controller/'
    type: annotation

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

account:
    resource: "@AppBundle/Controller/TransferController.php"
    prefix:   /api
    type:     annotation

user:
    resource: "@AppBundle/Controller/UserController.php"
    prefix:   /api
    type:     annotation

registration:
    path:      /register
    defaults:  { _controller: AppBundle:Registration:register}
    methods:  [POST]